# Numpy

###### Ref: https://numpy.org/doc/stable/user/quickstart.html

In [1]:
import numpy as np

## creating Numpy array form python lists

In [2]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [3]:
np.array([3.14, 2,3,4,5]) # np tu conveert ve sang dang thap nhat int -> float

array([3.14, 2.  , 3.  , 4.  , 5.  ])

In [4]:
# Su dung dtype de dinh dang kieu du lieu
np.array([1,2,3,4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [5]:
a1 = np.array([1,2,3,4])

In [6]:
type(a1)

numpy.ndarray

In [7]:
a2 = np.array([[1,2,3],[4,5,6]])
type(a2)

numpy.ndarray

In [8]:
a2.shape

(2, 3)

In [9]:
a2.ndim # so chieu cua mang

2

In [10]:
a1.ndim

1

In [11]:
a2.dtype

dtype('int64')

In [12]:
a2.size # tong so element trong a2

6

## Create Numpy Array form scratch
#### Su dung san nhung ham co san trong numpy (build in)

### zeros, ones, full, arange, linspace

### zeros

In [13]:
np.zeros([2,4]) # truyen vao hinh dang 2 hang 4 cut note: shape = (2,4) or [2,4]

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
np.zeros([2,4], dtype= int)  # set kieu du lieu cho bien

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

### ones

In [15]:
np.ones((3,5)) # truyen vao shape mong muon vd 3 hang 5 cot

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [16]:
np.ones((6,6), dtype=float)# truyen vao kieu du lieu mong muon

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

### arange

In [17]:
np.arange(4,21, 3) # diem bat dau va diem ket thuc va khaong cach

array([ 4,  7, 10, 13, 16, 19])

In [18]:
np.arange(1,20,5, dtype= float) # truyen vao kieu du lieu mong muon

array([ 1.,  6., 11., 16.])

### full

In [19]:
np.full([3,5], 21, dtype=float) # share va kieu du lieu muon tao ra

array([[21., 21., 21., 21., 21.],
       [21., 21., 21., 21., 21.],
       [21., 21., 21., 21., 21.]])

### linspace

In [20]:
np.linspace(0,1, 5) # diem bat dau va diem ket thuc va dc chia thanh 5 diem khoang cach giong nhau

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

### random

In [21]:
np.random.random((4,4)) # truyen vao size cho ham random vd: 4x4 va tuong duong voi np.random.rand(4,4)

array([[0.56708929, 0.36538169, 0.24188082, 0.82509087],
       [0.24064101, 0.16992507, 0.16619007, 0.10210274],
       [0.1716763 , 0.55291134, 0.46059092, 0.58719884],
       [0.1576296 , 0.19362291, 0.76117238, 0.40353061]])

In [22]:
np.random.rand(4,4)

array([[0.01915078, 0.08975975, 0.88151697, 0.99872822],
       [0.89427196, 0.33857789, 0.21082305, 0.06557367],
       [0.12542264, 0.88939914, 0.43687584, 0.26678816],
       [0.38813407, 0.58716869, 0.73298956, 0.38193366]])

In [23]:
# Seed for reproducibility
np.random.seed(0)
np.random.random((4,4)) #Seed dung de tao ra ham random ngau nhien o bat ky dau deu giongs nhau 

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318],
       [0.4236548 , 0.64589411, 0.43758721, 0.891773  ],
       [0.96366276, 0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606, 0.0871293 ]])

In [24]:
# normal: randome so ngau nhien
np.random.normal(3,0.0001, (3,3)) # 3: , 0.1 la do lech chua (3,3) = size

array([[3.00004439, 3.00003337, 3.00014941],
       [2.99997948, 3.00003131, 2.99991459],
       [2.9997447 , 3.00006536, 3.00008644]])

In [25]:
# randint:
np.random.randint(0, 10, (4,5)) # so ngau hien tu 0 -> 10 

array([[7, 2, 0, 0, 4],
       [5, 5, 6, 8, 4],
       [1, 4, 9, 8, 1],
       [1, 7, 9, 9, 3]])

## Array Indexing and Slicing
### Indexing

#### One-dimensional subarray

In [26]:
# tao mot array tu 0-> 20 voi size = 6
x1 = np.random.randint(20, size = 6)

In [27]:
x1

array([ 6, 11, 14, 18,  0, 14])

In [28]:
# tiep can vi tri thu 4
x1[4], x1[0], x1[-1] # -1 la vi tri cuoi cung

(0, 6, 14)

#### Muti-dimensional array

In [29]:
x2 = np.random.randint(20, size = (3,4))

In [30]:
x2

array([[ 3, 12, 10, 11],
       [ 4,  6,  4, 15],
       [ 3, 12,  4,  8]])

In [31]:
x2[1,2] # index cot 1 hang 2

4

In [32]:
x2[1,2] = 21 # change index cot 1 hang 2

In [33]:
x2

array([[ 3, 12, 10, 11],
       [ 4,  6, 21, 15],
       [ 3, 12,  4,  8]])

### Slicing
x[start:storp:step]

In [34]:
# khoang muon cat (diem dau, diem cuoi) vd: lay 3 gia tri dau
x1

array([ 6, 11, 14, 18,  0, 14])

In [35]:
x1[0:3] # lay 3 gia tri dau tien

array([ 6, 11, 14])

In [36]:
x1[2: 4]

array([14, 18])

In [37]:
x1[::2]# lay theo cac step vd cach nhau 2

array([ 6, 14,  0])